### ISSUE TITLE
Area names are sometimes MASSIVE

### ISSUE THREAD

**Issue by morganfeeney** [mozilla/css-grid-inspector#31]
HI, I've been making good use of the Grid inspector. I have started to use it for "full-bleed" style imagery where, in some cases I want the images to be edge to edge, yet the content should be indented in some kind of gutter. I have ran into a couple of instances where this makes the labels of the named areas so large I cannot see my work.

Please see reduced test case: https://codepen.io/morganfeeney/pen/ZarpPZ?editors=1100

...and screenshot of what I see just in case:

![image](https://user-images.githubusercontent.com/1900222/33017505-80d666aa-cdea-11e7-984a-4e92156cd225.png)

Another example:
![image](https://user-images.githubusercontent.com/1900222/33041400-17e376fa-ce36-11e7-8ce0-44b85ad6c39c.png)

And the pièce de résistance:
![image](https://user-images.githubusercontent.com/1900222/33041446-3cf0c3f8-ce36-11e7-9cd9-d750f70eee91.png)

Sorry but the last 2 examples are being developed in private so I can't give access, however the reduced test case is the same code pretty much. I think this issue gets bigger with more content and more page.

**Comment by morganfeeney** [comment]
Hi @jensimmons , I just realised this repo is/was for the extension, have I created an issue in the wrong repo?

**Comment by morganfeeney** [comment]
OK, I may as well carry on talking to myself, I had to raise a bug via Mozilla to get this dealt with which is now resolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1424880

**Comment by jensimmons** [comment]
@morganfeeney So sorry — I know GitHub sent me notifications when you posted months ago, but I missed them. I saw this last comment come through my inbox this morning. Yes, this is not the right place to file that bug. Sorry. This was the repo for the very first version of the Grid Inspector, when it was a Firefox Add-on. The goal was always to get it into Firefox proper, and when that happened, we stopped paying attention to this space. Bugzilla is the correct place to file bugs about the Grid Inspector now — and you figured that out! I'm glad, because that's where our engineers will see things and can jump  on them. Which they now have. Thanks so much for filing a bug. And for reminding me we should close down this space.
